services:
  tradis-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: coracoo/tradis:server_b_0.1.0
    container_name: tradis-server-backend
    restart: unless-stopped
    ports:
      - "33333:3002"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3002
      - GIN_MODE=release

  tradis-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: coracoo/tradis:server_f_0.1.0
    container_name: tradis-server-frontend
    restart: unless-stopped
    ports:
      - "33332:80"
    depends_on:
      - tradis-backend
