services:
    web:
        environment:
            NGINX_HOST: foobar.com
            NGINX_PORT: "80"
        image: nginx
        ports:
            - 10002:80
        volumes:
            - ./templates:/etc/nginx/templates
